name: testsendbird
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.4
  get: ^4.6.6
  scrollable_positioned_list: ^0.3.8
  sendbird_chat_sdk: ^4.2.2
  sendbird_chat_widget: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  husky: ^0.1.7
  lint_staged: ^0.5.1
  commitlint_cli: ^0.7.1

lint_staged:
  "lib/**.dart": dart format -l 120 && dart analyze --fatal-infos --fatal-warnings

flutter:
  uses-material-design: true
